# Generated by Django 4.2.3 on 2023-07-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightbuyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='bikename',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='biketype',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='budget',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='company',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='specification',
            field=models.CharField(max_length=250),
        ),
    ]
