# Generated by Django 4.2.3 on 2023-07-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rightbuyapp', '0002_alter_vehicle_bikename_alter_vehicle_biketype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='rollno',
            new_name='phno',
        ),
    ]
