# Generated by Django 4.2.3 on 2023-09-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightbuyapp', '0003_rename_rollno_login_phno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scodedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bike_images/')),
                ('heading', models.CharField(max_length=250)),
                ('para', models.CharField(max_length=250)),
            ],
        ),
    ]
