# Generated by Django 4.2.3 on 2023-09-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightbuyapp', '0004_scodedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scodedetail',
            name='heading',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='scodedetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='scodedetail',
            name='para',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
